development:
  cloud_name: stanleycloudinary
  api_key: '762617237622639'
  api_secret: i2LT-oa2ZARKqRiZGNxKIm8v-sA
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: stanleycloudinary
  api_key: '762617237622639'
  api_secret: i2LT-oa2ZARKqRiZGNxKIm8v-sA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: stanleycloudinary
  api_key: '762617237622639'
  api_secret: i2LT-oa2ZARKqRiZGNxKIm8v-sA
  enhance_image_tag: true
  static_image_support: false